<?php

/**
 * Implements hook_civicrm_buildForm.
 *
 * Alters contribution forms to hide "site id" field and populate it from the url.
 *
 * @param string $formName
 * @param CRM_Core_Form $form
 */
function civicrm_org_members_civicrm_buildForm($formName, &$form) {
  if ($formName == 'CRM_Contribute_Form_Contribution_Main' && $form->elementExists('onbehalf[custom_193]')) {
    $form->removeElement('onbehalf[custom_193]');
    $form->addElement('hidden', 'onbehalf[custom_193]');
    $sid = CRM_Utils_Array::value('sid', $_GET);
    if ($sid && preg_match('/^[a-zA-Z0-9]{32}$/', $sid)) {
      $form->setDefaults(array('onbehalf[custom_193]' => $sid));
    }
  }
}

/**
 * Implements hook_civicrm_sumfields_definitions()
 *
 * Adds summary fields to calculate total contributions to the project
 *
 * @param $custom
 */
function civicrm_org_members_civicrm_sumfields_definitions(&$custom) {
  $custom['fields']['partner_total_twelve_months'] = array(
    'label' => 'Finanancial and In-Kind Contributions (12 months)',
    'data_type' => 'Money',
    'html_type' => 'Text',
    'weight' => '15',
    'text_length' => '32',
    // Tally all financial contributions, code contributions (type 18) get multiplied
    'trigger_sql' => '(
      SELECT COALESCE(SUM(IF(cont1.financial_type_id = 18, cont1.total_amount*10, cont1.total_amount)),0)
      FROM civicrm_contribution cont1
      LEFT JOIN civicrm_contribution_soft soft
        ON soft.contribution_id = cont1.id
      WHERE (cont1.contact_id = NEW.contact_id OR soft.contact_id = NEW.contact_id)
        AND CAST(cont1.receive_date AS DATE) BETWEEN DATE_SUB(NOW(), INTERVAL 12 MONTH) AND NOW()
        AND cont1.contribution_status_id = 1 AND cont1.financial_type_id IN (1,2,10,12,19,11,13,5,6,18)
      )',
    'trigger_table' => 'civicrm_contribution',
    'optgroup' => 'civi',
  );
  $custom['optgroups']['civi'] = array(
    'title' => 'Contributors',
    'fieldset' => 'CiviCRM Website',
    'component' => 'CiviContribute',
  );
}